### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [the-codetrane/rsc-meeting-notes-app#3]
rsc-meeting-notes-app/.env has been compromised and your login/pwd are now visible on this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

Hope this will help you :)

**Comment by the-codetrane** [comment]
Thanks! I've removed the .env file from the project. Thanks for looking out.

**Comment by ousamabenyounes** [comment]
It is a pleasure to help other developpers!

we can still access your credential with git history:

https://github.com/the-codetrane/rsc-meeting-notes-app/commit/da9cdb4ee2a6112a2f0e5466f403319e88046a3a

I recommand you two soltuion.
you remove the project from github. Clean and recreate it so no history will be visible...

Or you follow this github recommandation: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

good luck!
